services:
  api:
    build: .
    container_name: fastapi-service
    ports:
      - "8100:8000"
    env_file: .env
    depends_on:
      - redis
    networks:
      - agrosavia-network   # ğŸ‘ˆ ConexiÃ³n explÃ­cita a la red existente

  redis:
    image: redis:7
    container_name: redis-service
    ports:
      - "6380:6379"
    networks:
      - agrosavia-network   # ğŸ‘ˆ Igual aquÃ­

networks:
  agrosavia-network:
    external: true          # ğŸ‘ˆ Indicamos que ya existe, sin driver ni name
